name: "Run"
on:
  workflow_dispatch:
  push:
    branches:
    - master
jobs:
  run:
    name: Run
    strategy:
      matrix:
        include:
        - target: x86_64-linux
        - target: aarch64-linux
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v24
      with:
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixpkgs-unstable.tar.gz
        extra_nix_config: extra-platforms = ${{matrix.target}}
    - name: Run ${{matrix.target}}.hello
      run: |
        nix run nixpkgs#legacyPackages.${{matrix.target}}.hello
