name: "Run"
on:
  workflow_dispatch:
  push:
    branches:
    - master
jobs:
  run:
    name: Run
    strategy:
      matrix:
        host: [run01, run02, run03, run04]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{secrets.TS_OAUTH_CLIENT_ID}}
        oauth-secret: ${{secrets.TS_OAUTH_SECRET}}
        hostname: ${{matrix.host}}
        tags: tag:ci
    - name: Wait
      run: |
        sleep 30
    - name: Test
      run: |
        ping -c 4 run01
        ping -c 4 run02
        ping -c 4 run03
        ping -c 4 run04
